TARGET = main.exe
INCLUDEPATH = "C:\Users\eef\SDL2\x86_64-w64-mingw32\include\SDL2"
LIBRARYPATH = "C:\Users\eef\SDL2\x86_64-w64-mingw32\lib"
cc = g++
SOURCES = "src/main.cpp" "src/Map.cpp" "src/Mech.cpp" "src/Mushroom.cpp" "src/Player.cpp" "src/Gui.cpp" "src/Entity.cpp" "src/Collider.cpp" "src/PlayInput.cpp" "src/EditInput.cpp"

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(cc) --std=c++14 -I $(INCLUDEPATH) -L $(LIBRARYPATH) -o main $(SOURCES) -lmingw32 -lSDL2main -lSDL2