TARGET = main.exe
INCLUDEPATH = "C:\Users\eef\SDL2\x86_64-w64-mingw32\include\SDL2"
LIBRARYPATH = "C:\Users\eef\SDL2\x86_64-w64-mingw32\lib"
cc = g++
SOURCES = "src/main.cpp" "src/Map.cpp" "src/entities/Mech.cpp" "src/Mushroom.cpp" "src/entities/Player.cpp" "src/Gui.cpp" "src/entities/Entity.cpp" "src/Collider.cpp" "src/controller/PlayInput.cpp" "src/controller/EditInput.cpp" "src/controller/InputFactory.cpp" "src/Camera.cpp" "src/entities/EntityManager.cpp" "src/TextureManager.cpp" "src/WindowManager.cpp"

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(cc) --std=c++14 -I $(INCLUDEPATH) -L $(LIBRARYPATH) -o main $(SOURCES) -lmingw32 -lSDL2main -lSDL2